### ISSUE TITLE
Remove API key from code

### ISSUE THREAD

**Issue by itsjustaplant** [meghnavarma0/movie-magic#10]
I suggest you to remove your api key which supposed to remain secret. 
Do this 
`const API_KEY = "--insert api key here--";`
Instead of
`const API_KEY = 9377XXXX;`

This can be fixed by just removing the key from the code. Thus, any person who wants to fork and clone the repo must have the key.

**Comment by meghnavarma0** [comment]
Hey @itsjustaplant ,

Thanks for pointing that out!
